name: letwork
description: "A Flutter marketplace style business listing app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # iOS tarzı ikonlar
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7


  # NETWORK VE CACHE
  dio: ^5.1.0                     # API istekleri için (modern & güçlü)
  cached_network_image: ^3.2.3    # Resimleri cache’leyerek yükler

  # STATE MANAGEMENT
  flutter_bloc: ^9.0.0            # Cubit/BLoC yönetimi

  # HARİTA & KONUM
  flutter_map: ^8.1.0             # Leaflet tabanlı harita
  geolocator: ^9.0.1              # Lokasyon alma
  latlong2: ^0.9.0                # Koordinat desteği (Map ile uyumlu)

  # UI VE RENDER
  flutter_svg: ^2.0.9             # SVG ikonları
  image_picker: ^1.1.2            # Galeri/kameradan görsel alma
  flutter_rating_bar: ^4.0.0


  # ROUTING
  go_router: ^14.8.1              # Sayfa geçişleri, nested routing

  # TEXT CHECKING
  bad_words: ^0.3.0               # Küfür/swear filter için (yorumlar vs.)

  # TOAST, LOCAL STORAGE VS İLERİDE EKLENEBİLİR
  fluttertoast: ^8.2.1            # Kullanıcıya bilgi göstermek için
  shared_preferences: ^2.0.15     # Kullanıcı verisi tutmak için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Letwork_Logo.png

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont.ttf
