name: letwork
description: "A Flutter marketplace style business listing app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  # iOS tarzı ikonlar
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  intl: ^0.20.2  # Use the latest version available
  flutter_map_location_marker: ^10.0.2
  url_launcher: ^6.3.1
  map_launcher: ^3.5.0





  # NETWORK VE CACHE
  dio: ^5.1.0                     # API istekleri için (modern & güçlü)
  cached_network_image: ^3.2.3    # Resimleri cache’leyerek yükler

  # STATE MANAGEMENT
  flutter_bloc: ^9.0.0            # Cubit/BLoC yönetimi

  # HARİTA & KONUM
  flutter_map: ^8.1.0             # Leaflet tabanlı harita
  geolocator: ^13.0.4              # Lokasyon alma
  latlong2: ^0.9.0                # Koordinat desteği (Map ile uyumlu)

  # UI VE RENDER
  flutter_svg: ^2.0.9             # SVG ikonları
  image_picker: ^1.1.2            # Galeri/kameradan görsel alma
  flutter_rating_bar: ^4.0.0



  # ROUTING
  go_router: ^15.0.0              # Sayfa geçişleri, nested routing

  # TEXT CHECKING
  bad_words: ^0.3.0               # Küfür/swear filter için (yorumlar vs.)

  # TOAST, LOCAL STORAGE VS İLERİDE EKLENEBİLİR
  fluttertoast: ^8.2.1            # Kullanıcıya bilgi göstermek için
  shared_preferences: ^2.0.15     # Kullanıcı verisi tutmak için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true

  assets:
    - assets/Letwork_Logo.png
    - assets/default.png
    - assets/pin.png

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont.ttf
